# Generated by Django 5.1.6 on 2025-08-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estagiario_digital'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('uuid', models.CharField(max_length=128)),
                ('verb', models.CharField(blank=True, max_length=10, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=128, null=True)),
                ('body', models.JSONField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('query_string', models.CharField(blank=True, max_length=256, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('uuid', models.CharField(max_length=128)),
                ('endpoint', models.CharField(blank=True, max_length=128, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
